export const libs = [
  {
    id: 1,
    nomi: "Abu Ali ibn Sino nomidagi Buxoro viloyati axborot-kutubxona markazi",
    manzil: "Buxoro sh. I. Mo‘minov k-si, 6-uy",
    ish_vaqti: "8:00 dan 18:00 gacha",
    dam_olish_kunlari: ["Yakshanba"],
  },
  {
    id: 2,
    nomi: "Buxoro viloyati ko‘zi ojizlar kutubxonasi",
    manzil: "Buxoro, Abay ko‘chasi, 6/31",
    ish_vaqti: "9:00 dan 18:00 gacha",
    dam_olish_kunlari: ["Shanba", "Yakshanba"],
  },
  {
    id: 3,
    nomi: "Olot tuman axborot-kutubxona markazi",
    manzil: "Bunyodkor MFY, Bunyodkor ko‘chasi, 50-uy",
    ish_vaqti: "8:00 dan 18:00 gacha, Shanba 12:00gacha",
    dam_olish_kunlari: ["Yakshanba"],
  },
  {
    id: 4,
    nomi: "Buxoro tuman axborot-kutubxona markazi",
    manzil: "Ibn Sino ko‘chasi, 1-uy",
    ish_vaqti: "8:00 dan 18:00 gacha, Shanba 12:00gacha",
    dam_olish_kunlari: ["Yakshanba"],
  },
  {
    id: 5,
    nomi: "Vobkent tuman axborot-kutubxona markazi",
    manzil: "Ahmad Donish ko‘chasi, 44-uy",
    ish_vaqti: "8:00 dan 18:00 gacha, Shanba 12:00gacha",
    dam_olish_kunlari: ["Yakshanba"],
  },
  {
    id: 6,
    nomi: "Jondor tuman axborot-kutubxona markazi",
    manzil: "Mahmud Torobiy ko‘chasi, 46-uy",
    ish_vaqti: "8:00 dan 18:00 gacha, Shanba 12:00gacha",
    dam_olish_kunlari: ["Yakshanba"],
  },
  {
    id: 7,
    nomi: "Kogon tuman axborot-kutubxona markazi",
    manzil: "Niyozhoji QFY, Niyozhoji qishlog‘i",
    ish_vaqti: "8:00 dan 18:00 gacha, Shanba 12:00gacha",
    dam_olish_kunlari: ["Yakshanba"],
  },
  {
    id: 8,
    nomi: "Kogon shahar axborot-kutubxona markazi",
    manzil: "Vatanparvar ko‘chasi, 4-uy",
    ish_vaqti: "8:00 dan 18:00 gacha, Shanba 12:00gacha",
    dam_olish_kunlari: ["Yakshanba"],
  },
  {
    id: 9,
    nomi: "Peshko tuman axborot-kutubxona markazi",
    manzil: "Amir Temur ko‘chasi, 6-uy",
    ish_vaqti: "8:00 dan 18:00 gacha, Shanba 12:00gacha",
    dam_olish_kunlari: ["Yakshanba"],
  },
  {
    id: 10,
    nomi: "Romitan tuman axborot-kutubxona markazi",
    manzil: "Ibn Sino MFY, Yangi Hayot ko‘chasi, 100-uy",
    ish_vaqti: "8:00 dan 18:00 gacha, Shanba 12:00gacha",
    dam_olish_kunlari: ["Yakshanba"],
  },
  {
    id: 11,
    nomi: "Shofirkon tuman axborot-kutubxona markazi",
    manzil: "Fayzulla Xo‘jayev ko‘chasi, 9-uy",
    ish_vaqti: "8:00 dan 18:00 gacha, Shanba 12:00gacha",
    dam_olish_kunlari: ["Yakshanba"],
  },
  {
    id: 12,
    nomi: "Qorako‘l tuman axborot-kutubxona markazi",
    manzil: "Ulug‘bek ko‘chasi, 229-uy",
    ish_vaqti: "Ma’lumot yo‘q",
    dam_olish_kunlari: [],
  },
  {
    id: 13,
    nomi: "Qorovulbozor tuman axborot-kutubxona markazi",
    manzil: "Geologlar ko‘chasi, 1-uy",
    ish_vaqti: "8:00 dan 18:00 gacha, Shanba 12:00gacha",
    dam_olish_kunlari: ["Yakshanba"],
  },
  {
    id: 14,
    nomi: "G‘ijduvon tuman axborot-kutubxona markazi",
    manzil: "A. G‘ijduvoniy shoh ko‘chasi, 70-uy",
    ish_vaqti: "8:00 dan 18:00 gacha, Shanba 12:00gacha",
    dam_olish_kunlari: ["Yakshanba"],
  },
  {
    id: 15,
    nomi: "Narshaxiy nomidagi Buxoro viloyat bolalar kutubxonasi",
    manzil: "Buxoro shahri, X. Ibodov ko‘chasi, 4-uy",
    ish_vaqti: "8:00 dan 18:00 gacha",
    dam_olish_kunlari: ["Shanba", "Yakshanba"],
  },
  {
    id: 16,
    nomi: "Buxoro Yoshlar Markazi Kutubxonasi",
    manzil: "G‘ijduvon ko‘chasi, Yoshlar markazi binosi",
    ish_vaqti: "Dushanba – Shanba: 09:00 – 18:00",
    dam_olish_kunlari: ["Yakshanba"],
  },
  {
    id: 17,
    nomi: "Abu Ali ibn Sino nomidagi Tibbiyot Kutubxonasi",
    manzil: "Ibn Sino ko‘chasi, Buxoro Tibbiyot Instituti hududi",
    ish_vaqti: "Dushanba – Jum’a: 08:30 – 17:00, Shanba: qisqa yoki yopiq",
    dam_olish_kunlari: ["Yakshanba"],
  },
];
